# Generated by Django 4.1.7 on 2023-05-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/image_vehicule')),
                ('prix_regulier', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('couleur', models.CharField(max_length=100)),
                ('kilometrage', models.PositiveIntegerField()),
                ('nombre_de_place', models.PositiveIntegerField()),
                ('carburant', models.CharField(max_length=100)),
                ('puissance', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
