# Generated by Django 4.1.7 on 2023-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_login_registre_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(upload_to='image_vehicule/'),
        ),
    ]
