# Generated by Django 4.1.7 on 2023-05-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_vehicule_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicule',
            table='vehicule',
        ),
    ]
