# Generated by Django 4.1.7 on 2023-06-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_vehicule_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(upload_to='static/image_vehicule/'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.registre')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vehicule')),
            ],
        ),
    ]
