# Generated by Django 4.1.7 on 2023-06-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_vehicule_image_contrat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrat',
            table='contrat',
        ),
    ]
